// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* mashup.h
   Generated by wsdl2h 2.8.12 from t.wsdl calc.wsdl mashup.wsdl and typemap.dat
   2012-12-10 00:19:43 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2012 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on mashup.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Use wsdl2h option -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://tempuri.org/t.xsd"
ns2 = "http://tempuri.org/t.xsd/Service.wsdl"
ns3 = "urn:calc"
ns4 = "http://websrv.cs.fsu.edu/~engelen/calc.wsdl"
ns5 = "urn:daystoxmas"
ns6 = "http://www.genivia.com/mashup.wsdl"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/t.xsd"
//gsoap ns1   schema namespace:	http://tempuri.org/t.xsd
//gsoap ns1   schema form:	unqualified

#define SOAP_NAMESPACE_OF_ns2	"http://tempuri.org/t.xsd/Service.wsdl"
//gsoap ns2   schema namespace:	http://tempuri.org/t.xsd/Service.wsdl
//gsoap ns2   schema form:	unqualified

#define SOAP_NAMESPACE_OF_ns3	"urn:calc"
//gsoap ns3   schema namespace:	urn:calc
//gsoap ns3   schema form:	unqualified

#define SOAP_NAMESPACE_OF_ns4	"http://websrv.cs.fsu.edu/~engelen/calc.wsdl"
//gsoap ns4   schema namespace:	http://websrv.cs.fsu.edu/~engelen/calc.wsdl
//gsoap ns4   schema form:	unqualified

#define SOAP_NAMESPACE_OF_ns5	"urn:daystoxmas"
//gsoap ns5   schema namespace:	urn:daystoxmas
//gsoap ns5   schema form:	qualified

#define SOAP_NAMESPACE_OF_ns6	"http://www.genivia.com/mashup.wsdl"
//gsoap ns6   schema namespace:	http://www.genivia.com/mashup.wsdl
//gsoap ns6   schema form:	unqualified

#define SOAP_NAMESPACE_OF_empty	""
//gsoap empty schema namespace:	
//gsoap empty schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "urn:daystoxmas":daystoxmas.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/t.xsd                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/t.xsd/Service.wsdl                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   urn:calc                                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://websrv.cs.fsu.edu/~engelen/calc.wsdl                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   urn:daystoxmas                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://www.genivia.com/mashup.wsdl                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/t.xsd                                                 *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "http://tempuri.org/t.xsd":gmt

/// "http://tempuri.org/t.xsd":gmt is a complexType.
struct _ns1__gmt
{
};


/// Top-level root element "http://tempuri.org/t.xsd":gmtResponse

/// "http://tempuri.org/t.xsd":gmtResponse is a complexType.
struct _ns1__gmtResponse
{
/// Element param-1 of type xs:dateTime.
    time_t*                              param_1                        0;	///< Nillable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/t.xsd/Service.wsdl                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   urn:calc                                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://websrv.cs.fsu.edu/~engelen/calc.wsdl                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   urn:daystoxmas                                                           *
 *                                                                            *
\******************************************************************************/



/// Top-level root element "urn:daystoxmas":commingtotown

/// "urn:daystoxmas":commingtotown is a complexType.
struct _ns5__commingtotown
{
/// Element days of type xs:int.
    int                                  days                           1;	///< Required element.
};

/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://www.genivia.com/mashup.wsdl                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/t.xsd                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/t.xsd                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/t.xsd/Service.wsdl                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/t.xsd/Service.wsdl                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   urn:calc                                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   urn:calc                                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://websrv.cs.fsu.edu/~engelen/calc.wsdl                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://websrv.cs.fsu.edu/~engelen/calc.wsdl                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   urn:daystoxmas                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   urn:daystoxmas                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://www.genivia.com/mashup.wsdl                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://www.genivia.com/mashup.wsdl                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	Service 
//gsoap ns2  service type:	ServicePortType 
//gsoap ns2  service port:	http://localhost:80 
//gsoap ns2  service namespace:	http://tempuri.org/t.xsd/Service.wsdl 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap ns3  service name:	calc 
//gsoap ns3  service type:	calcPortType 
//gsoap ns3  service port:	http://websrv.cs.fsu.edu/~engelen/calcserver.cgi 
//gsoap ns3  service namespace:	urn:calc 
//gsoap ns3  service transport:	http://schemas.xmlsoap.org/soap/http 

//gsoap ns6  service name:	mashup 
//gsoap ns6  service type:	PortType 
//gsoap ns6  service port:	http://www.cs.fsu.edu/~engelen/mashup.cgi 
//gsoap ns6  service namespace:	http://www.genivia.com/mashup.wsdl 
//gsoap ns6  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage WSDL Definitions

@section WSDL_bindings Service Bindings

  - @ref Service

  - @ref calc

  - @ref mashup

@section WSDL_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page Service Binding "Service"

@section Service_service Service Documentation "Service"
gSOAP 2.8.12 generated service definition

@section Service_operations Operations of Binding  "Service"

  - @ref __ns2__gmt

@section Service_ports Endpoints of Binding  "Service"

  - http://localhost:80

Note: use wsdl2h option -N to change the service binding prefix name

*/

/**

@page calc Binding "calc"

@section calc_service Service Documentation "calc"
Simple calculator service

@section calc_operations Operations of Binding  "calc"

  - @ref ns3__add

  - @ref ns3__sub

  - @ref ns3__mul

  - @ref ns3__div

  - @ref ns3__pow

@section calc_ports Endpoints of Binding  "calc"

  - http://websrv.cs.fsu.edu/~engelen/calcserver.cgi

Note: use wsdl2h option -N to change the service binding prefix name

*/

/**

@page mashup Binding "mashup"

@section mashup_operations Operations of Binding  "mashup"

  - @ref __ns6__dtx

@section mashup_ports Endpoints of Binding  "mashup"

  - http://www.cs.fsu.edu/~engelen/mashup.cgi

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   Service                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns2__gmt                                                               *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns2__gmt" of service binding "Service"

/**

Operation details:
Service definition of function t__gmt

  - SOAP document/literal style messaging

  - Addressing input action: "http://tempuri.org/t.xsd/Service.wsdl/ServicePortType/gmt"

  - Addressing input output action: "http://tempuri.org/t.xsd/Service.wsdl/ServicePortType/gmtResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns2__gmt(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct _ns1__gmt*                   ns1__gmt,
    // output parameters:
    struct _ns1__gmtResponse*           ns1__gmtResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns2__gmt(
    struct soap *soap,
    // input parameters:
    struct _ns1__gmt*                   ns1__gmt,
    // output parameters:
    struct _ns1__gmtResponse*           ns1__gmtResponse
  );
@endcode

*/

//gsoap ns2  service method-protocol:	gmt SOAP
//gsoap ns2  service method-style:	gmt document
//gsoap ns2  service method-encoding:	gmt literal
//gsoap ns2  service method-action:	gmt ""
//gsoap ns2  service method-output-action:	gmt http://tempuri.org/t.xsd/Service.wsdl/ServicePortType/gmtResponse
int __ns2__gmt(
    struct _ns1__gmt*                   ns1__gmt,	///< Input parameter
    struct _ns1__gmtResponse*           ns1__gmtResponse	///< Output parameter
);

/**

@page Service Binding "Service"

@section Service_policy_enablers Policy Enablers of Binding  "Service"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   calc                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns3__add                                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "ns3__add" of service binding "calc"

/**

Operation details:
Sums two values

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Addressing input action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/add"

  - Addressing input output action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/addResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns3__add(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns3__add(
    struct soap *soap,
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

*/

//gsoap ns3  service method-protocol:	add SOAP
//gsoap ns3  service method-style:	add rpc
//gsoap ns3  service method-encoding:	add http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns3  service method-action:	add ""
//gsoap ns3  service method-output-action:	add http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/addResponse
int ns3__add(
    double                              a,	///< Input parameter
    double                              b,	///< Input parameter
    double                             *result	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns3__sub                                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "ns3__sub" of service binding "calc"

/**

Operation details:
Subtracts two values

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Addressing input action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/sub"

  - Addressing input output action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/subResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns3__sub(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns3__sub(
    struct soap *soap,
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

*/

//gsoap ns3  service method-protocol:	sub SOAP
//gsoap ns3  service method-style:	sub rpc
//gsoap ns3  service method-encoding:	sub http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns3  service method-action:	sub ""
//gsoap ns3  service method-output-action:	sub http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/subResponse
int ns3__sub(
    double                              a,	///< Input parameter
    double                              b,	///< Input parameter
    double                             *result	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns3__mul                                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "ns3__mul" of service binding "calc"

/**

Operation details:
Multiplies two values

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Addressing input action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/mul"

  - Addressing input output action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/mulResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns3__mul(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns3__mul(
    struct soap *soap,
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

*/

//gsoap ns3  service method-protocol:	mul SOAP
//gsoap ns3  service method-style:	mul rpc
//gsoap ns3  service method-encoding:	mul http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns3  service method-action:	mul ""
//gsoap ns3  service method-output-action:	mul http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/mulResponse
int ns3__mul(
    double                              a,	///< Input parameter
    double                              b,	///< Input parameter
    double                             *result	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns3__div                                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "ns3__div" of service binding "calc"

/**

Operation details:
Divides two values

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Addressing input action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/div"

  - Addressing input output action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/divResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns3__div(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns3__div(
    struct soap *soap,
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

*/

//gsoap ns3  service method-protocol:	div SOAP
//gsoap ns3  service method-style:	div rpc
//gsoap ns3  service method-encoding:	div http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns3  service method-action:	div ""
//gsoap ns3  service method-output-action:	div http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/divResponse
int ns3__div(
    double                              a,	///< Input parameter
    double                              b,	///< Input parameter
    double                             *result	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns3__pow                                                                 *
 *                                                                            *
\******************************************************************************/


/// Operation "ns3__pow" of service binding "calc"

/**

Operation details:
Raises a to b

  - http://schemas.xmlsoap.org/soap/encoding/ RPC encodingStyle="SOAP"

  - Addressing input action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/pow"

  - Addressing input output action: "http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/powResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns3__pow(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns3__pow(
    struct soap *soap,
    // input parameters:
    double                              a,
    double                              b,
    // output parameters:
    double                             *result
  );
@endcode

*/

//gsoap ns3  service method-protocol:	pow SOAP
//gsoap ns3  service method-style:	pow rpc
//gsoap ns3  service method-encoding:	pow http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns3  service method-action:	pow ""
//gsoap ns3  service method-output-action:	pow http://websrv.cs.fsu.edu/~engelen/calc.wsdl/calcPortType/powResponse
int ns3__pow(
    double                              a,	///< Input parameter
    double                              b,	///< Input parameter
    double                             *result	///< Output parameter
);

/**

@page calc Binding "calc"

@section calc_policy_enablers Policy Enablers of Binding  "calc"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   mashup                                                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns6__dtx                                                               *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns6__dtx" of service binding "mashup"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: "http://www.genivia.com/mashup.wsdl/PortType/dtx"

  - Addressing input output action: "http://www.genivia.com/mashup.wsdl/PortType/dtxResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns6__dtx(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _XML                                ns5__daystoxmas,
    // output parameters:
    struct _ns5__commingtotown*         ns5__commingtotown
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns6__dtx(
    struct soap *soap,
    // input parameters:
    _XML                                ns5__daystoxmas,
    // output parameters:
    struct _ns5__commingtotown*         ns5__commingtotown
  );
@endcode

*/

//gsoap ns6  service method-protocol:	dtx SOAP
//gsoap ns6  service method-style:	dtx document
//gsoap ns6  service method-encoding:	dtx literal
//gsoap ns6  service method-action:	dtx ""
//gsoap ns6  service method-output-action:	dtx http://www.genivia.com/mashup.wsdl/PortType/dtxResponse
int __ns6__dtx(
    _XML                                ns5__daystoxmas,	///< Input parameter
    struct _ns5__commingtotown*         ns5__commingtotown	///< Output parameter
);

/**

@page mashup Binding "mashup"

@section mashup_policy_enablers Policy Enablers of Binding  "mashup"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section ns1 Top-level root elements of schema "http://tempuri.org/t.xsd"

  - <ns1:gmt> @ref _ns1__gmt
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__gmt(struct soap*, struct _ns1__gmt*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__gmt(struct soap*, struct _ns1__gmt*);
    @endcode

  - <ns1:gmtResponse> @ref _ns1__gmtResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__gmtResponse(struct soap*, struct _ns1__gmtResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__gmtResponse(struct soap*, struct _ns1__gmtResponse*);
    @endcode

@section ns2 Top-level root elements of schema "http://tempuri.org/t.xsd/Service.wsdl"

@section ns3 Top-level root elements of schema "urn:calc"

@section ns4 Top-level root elements of schema "http://websrv.cs.fsu.edu/~engelen/calc.wsdl"

@section ns5 Top-level root elements of schema "urn:daystoxmas"

  - <ns5:daystoxmas> @ref _ns5__daystoxmas
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns5__daystoxmas(struct soap*, _XML);
    // Writer (returns SOAP_OK on success):
    soap_write__ns5__daystoxmas(struct soap*, _XML);
    @endcode

  - <ns5:commingtotown> @ref _ns5__commingtotown
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns5__commingtotown(struct soap*, struct _ns5__commingtotown*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns5__commingtotown(struct soap*, struct _ns5__commingtotown*);
    @endcode

@section ns6 Top-level root elements of schema "http://www.genivia.com/mashup.wsdl"

@section empty Top-level root elements of schema ""

*/

/* End of mashup.h */
